version: '3.8'

services:
  backend:
    build: ./cart-backend
    ports:
      - "5000:5000"
    env_file:
      - ./cart-backend/.env
    volumes:
      - ./cart-backend:/app
    depends_on:
      - mongo
    restart: always

  frontend:
    build: ./cart-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
